name: Release protocols

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  release:
    environment: buff
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1
        with:
            version: "1.50.0"
            github_token: ${{ github.token }}

      - name: Verify formatting
        run: buf format --diff --exit-code

      - name: Lint
        run: buf lint

      - name: Build schema
        run: buf build

      - name: Publish tagged schema to BSR
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: buf push --git-metadata
